# -*- coding: utf-8 -*-

from scrapy_djangoitem import DjangoItem
from HouseNew.models import *


class ProjectInfoItem(DjangoItem):
    django_model = ProjectInfoGuangzhou
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'PromotionName': '',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'DistrictName': 'DistrictName',
                  'RegionName': 'RegionName',
                  'ProjectAddress': '',
                  'ProjectType': '',
                  'OnSaleState': '',
                  'LandUse': '',
                  'HousingCount': '',
                  'Developer': 'Developer',
                  'FloorArea': 'FloorArea',
                  'TotalBuidlingArea': 'TotalBuildingArea',
                  'BuildingType': '',
                  'HouseUseType': '',
                  'PropertyRightsDescription': '',
                  'ProjectApproveData': '',
                  'ProjectBookingData': '',
                  'LssueDate': '',
                  'PresalePermitNumber': 'PresalePermitNumber',
                  'HouseBuildingCount': '',
                  'ApprovalPresaleAmount': 'ApprovalPresaleAmount',
                  'ApprovalPresaleArea': 'ApprovalPresaleArea',
                  'AveragePrice': '',
                  'EarliestStartDate': '',
                  'CompletionDate': '',
                  'EarliestOpeningTime': '',
                  'LatestDeliversHouseDate': '',
                  'PresaleRegistrationManagementDepartment': '',
                  'LandLevel': '',
                  'GreeningRate': '',
                  'FloorAreaRatio': '',
                  'ManagementFees': '',
                  'ManagementCompany': '',
                  'OtheRights': '',
                  'CertificateOfUseOfStateOwnedLand': 'CertificateOfUseOfStateOwnedLand',
                  'ConstructionPermitNumber': 'ConstructionPermitNumber',
                  'QualificationNumber': '',
                  'LandUsePermit': '',
                  'BuildingPermit': '',
                  'LegalPersonNumber': '',
                  'LegalPerson': '',
                  'SourceUrl': 'SourceUrl',
                  'Decoration': '',
                  'ParkingSpaceAmount': '',
                  'Remarks': '',
                  'ExtraJson': '',
                  }


class PresellInfoItem(DjangoItem):
    django_model = PresellInfoGuangzhou
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'PresalePermitNumber': 'PresalePermitNumber',
                  'TotalBuidlingArea': 'ConstructionTotalArea',
                  'ApprovalPresaleAmount': 'PresaleUnitCount',
                  'ApprovalPresaleArea': 'PresaleTotalBuildingArea',
                  'ApprovalPresaleHouseAmount': '',
                  'ApprovalPresaleHouseArea': '',
                  'PresaleBuildingAmount': 'PresaleBuildingAmount',
                  'ConstructionFloorCount': 'ConstructionFloorCount',
                  'BuiltFloorCount': 'BuiltFloorCount',
                  'PeriodsCount': 'PeriodsCount',
                  'ConstructionTotalArea': 'ConstructionTotalArea',
                  'GroundArea': 'GroundArea',
                  'UnderGroundArea': 'UnderGroundArea',
                  'PresaleTotalBuidlingArea': '',
                  'Contacts': 'Contacts',
                  'PresaleBuildingSupportingAreaInfo': '',
                  'PresaleHousingLandIsMortgage': '',
                  'ValidityDateStartDate': 'ValidityDateStartDate',
                  'ValidityDateClosingDate': 'ValidityDateClosingDate',
                  'LssueDate': 'LssueDate',
                  'LssuingAuthority': 'LssuingAuthority',
                  'PresaleRegistrationManagementDepartment': '',
                  'ValidityDateDescribe': '',
                  'ApprovalPresalePosition': '',
                  'LandUse': 'LandUse',
                  'EarliestStartDate': '',
                  'LatestDeliversHouseDate': '',
                  'EarliestOpeningDate': '',
                  'HouseSpread': 'HouseSpread',
                  'PresalePermitTie': '',
                  'PresaleHouseCount/PresaleUnitCount': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }


class HouseInfoItem(DjangoItem):
    django_model = HouseInfoGuangzhou
    fields_map = {'RecordTime': '',
                  'CaseTime': '',
                  'ProjectName': 'ProjectName',
                  'ProjectUUID': 'ProjectUUID',
                  'RealEstateProjectID': '',
                  'BuildingName': 'BuildingName',
                  'BuildingUUID': 'BuildingUUID',
                  'BuildingID': '',
                  'DistrictName': '',
                  'UnitName': 'UnitName',
                  'UnitID': '',
                  'UnitUUID': '',
                  'HouseNumber': 'HouseNumber',
                  'HouseName': 'HouseName',
                  'HouseID': '',
                  'HouseUUID': 'HouseUUID',
                  'Address': '',
                  'FloorName': 'FloorName',
                  'ActualFloor': 'ActualFloor',
                  'FloorCount': 'FloorCount',
                  'FloorType': '',
                  'FloorHight': 'FloorHight',
                  'UnitShape': 'UnitShape',
                  'UnitStructure': '',
                  'Rooms': '',
                  'Halls': '',
                  'Kitchens': 'Kitchens',
                  'Toilets': 'Toilets',
                  'Balconys': 'Balconys',
                  'UnenclosedBalconys': 'UnenclosedBalconys',
                  'HouseShape': '',
                  'Dwelling': '',
                  'ForecastBuildingArea': 'ForecastBuildingArea',
                  'ForecastInsideOfBuildingArea': 'ForecastInsideOfBuildingArea',
                  'ForecastPublicArea': 'ForecastPublicArea',
                  'MeasuredBuildingArea': 'MeasuredBuildingArea',
                  'MeasuredInsideOfBuildingArea': 'MeasuredInsideOfBuildingArea',
                  'MeasuredSharedPublicArea': 'MeasuredSharedPublicArea',
                  'MeasuredUndergroundArea': '',
                  'Toward': '',
                  'HouseType': '',
                  'HouseNature': '',
                  'Decoration': '',
                  'NatureOfPropertyRight': '',
                  'HouseUseType': 'HouseUseType',
                  'BuildingStructure': 'BuildingStructure',
                  'HouseSalePrice': '',
                  'SalePriceByBuildingArea': '',
                  'SalePriceByInsideOfBuildingArea': '',
                  'IsMortgage': '',
                  'IsAttachment': '',
                  'IsPrivateUse': '',
                  'IsMoveBack': '',
                  'IsSharedPublicMatching': '',
                  'SellState': '',
                  'SellSchedule': '',
                  'HouseState': 'HouseState',
                  'HouseStateLatest': 'HouseStateLatest',
                  'HouseLabel': 'HouseLabel',
                  'HouseLabelLatest': 'HouseLabelLatest',
                  'TotalPrice': '',
                  'Price': '',
                  'PriceType': '',
                  'DecorationPrice': '',
                  'Remarks': '',
                  'SourceUrl': 'SourceUrl',
                  'ExtraJson': '',
                  }


class BuildingInfoItem(DjangoItem):
    django_model = BuildingInfoGuangzhou
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'ProjectUUID': 'ProjectUUID',
                  'RealEstateProjectID': '',
                  'BuildingName': 'BuildingName',
                  'BuildingID': '',
                  'BuildingUUID': 'BuildingUUID',
                  'UnitName': '',
                  'UnitID': '',
                  'UnitUUID': '',
                  'PresalePermitNumber': '',
                  'Address': '',
                  'OnTheGroundFloor': '',
                  'TheGroundFloor': '',
                  'EstimatedCompletionDate': '',
                  'HousingCount': '',
                  'Floors': '',
                  'ElevatorHouse': '',
                  'IsHasElevator': '',
                  'ElevaltorInfo': '',
                  'BuildingStructure': '',
                  'BuildingType': '',
                  'BuildingHeight': '',
                  'BuildingCategory': '',
                  'Units': '',
                  'UnsoldAmount': '',
                  'BuildingAveragePrice': '',
                  'BuildingPriceRange': '',
                  'BuildingArea': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }


class PermitInfoItem(DjangoItem):
    django_model = PermitInfoGuangzhou
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'PermitType': 'PermitType',
                  'Content': 'Content',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }
