# coding = utf-8
from scrapy_djangoitem import DjangoItem
from HouseNew.models import *


class ProjectInfoItem(DjangoItem):
    django_model = ProjectBaseWulumuqi
    fields_map = {'RecordTime': 'CurTimeStamp',
                  'ProjectName': 'ProjectName',
                  'PromotionName': '',
                  'RealEstateProjectID': 'PropertyID',
                  'ProjectUUID': 'ProjectUUID',
                  'DistrictName': 'DistrictName',
                  'RegionName': 'RegionName',
                  'ProjectAddress': 'ProjectAddress',
                  'ProjectType': '',
                  'OnSaleState': 'OnSaleState',
                  'LandUse': 'LandUse',
                  'HousingCount': 'HousingCount',
                  'Developer': 'Developer',
                  'FloorArea': 'FloorArea',
                  'TotalBuidlingArea': 'TotalBuidlingArea',
                  'BuildingType': 'BuildingType',
                  'HouseUseType': '',
                  'PropertyRightsDescription': 'PropertyRightsDescription',
                  'ProjectApproveData': '',
                  'ProjectBookingData': '',
                  'LssueDate': '',
                  'PresalePermitNumber': '',
                  'HouseBuildingCount': '',
                  'ApprovalPresaleAmount': '',
                  'ApprovalPresaleArea': '',
                  'AveragePrice': '',
                  'EarliestStartDate': '',
                  'CompletionDate': 'CompletionDate',
                  'EarliestOpeningTime': '',
                  'LatestDeliversHouseDate': 'LatestDeliversHouseDate',
                  'PresaleRegistrationManagementDepartment': '',
                  'LandLevel': '',
                  'GreeningRate': 'GreeningRate',
                  'FloorAreaRatio': 'FloorAreaRatio',
                  'ManagementFees': 'ManagementFees',
                  'ManagementCompany': 'ManagementCompany',
                  'OtheRights': '',
                  'CertificateOfUseOfStateOwnedLand': '',
                  'ConstructionPermitNumber': '',
                  'QualificationNumber': '',
                  'LandUsePermit': '',
                  'BuildingPermit': '',
                  'LegalPersonNumber': '',
                  'LegalPerson': '',
                  'SourceUrl': 'SourceUrl',
                  'Decoration': 'ProjectDecoration',
                  'ParkingSpaceAmount': 'ParkingInfo',
                  'Remarks': '',
                  'ExtraJson': '',
                  }

class PresellInfoItem(DjangoItem):
    django_model = PresellInfoWulumuqi
    fields_map = {'RecordTime': 'CurTimeStamp',
                  'ProjectName': 'ApprovalProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'PresalePermitNumber': 'PresellName',
                  'TotalBuidlingArea': '',
                  'ApprovalPresaleAmount': 'num',
                  'ApprovalPresaleArea': 'area',
                  'ApprovalPresaleHouseAmount': 'resideavanum',
                  'ApprovalPresaleHouseArea': 'resideavaarea',
                  'PresaleBuildingAmount': '',
                  'ConstructionFloorCount': '',
                  'BuiltFloorCount': '',
                  'PeriodsCount': '',
                  'ConstructionTotalArea': '',
                  'GroundArea': '',
                  'UnderGroundArea': '',
                  'PresaleTotalBuidlingArea': '',
                  'Contacts': '',
                  'PresaleBuildingSupportingAreaInfo': '',
                  'PresaleHousingLandIsMortgage': '',
                  'ValidityDateStartDate': '',
                  'ValidityDateClosingDate': '',
                  'LssueDate': 'LssueDate',
                  'LssuingAuthority': 'LssuingAuthority',
                  'PresaleRegistrationManagementDepartment': '',
                  'ValidityDateDescribe': '',
                  'ApprovalPresalePosition': 'ApprovalPresalePosition',
                  'LandUse': '',
                  'EarliestStartDate': '',
                  'LatestDeliversHouseDate': '',
                  'EarliestOpeningDate': 'OpeningDate',
                  'HouseSpread': '',
                  'PresalePermitTie': 'PresellUUID',
                  'PresaleHouseCount/PresaleUnitCount': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }

class BuildingInfoItem(DjangoItem):
    django_model = BuildingInfoWulumuqi
    fields_map = {'RecordTime': 'CurTimeStamp',
                  'ProjectName': '',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'BuildingName': 'BuildingName',
                  'BuildingID': '',
                  'BuildingUUID': 'BuildingUUID',
                  'UnitName': '',
                  'UnitID': '',
                  'UnitUUID': '',
                  'PresalePermitNumber': '',
                  'Address': '',
                  'OnTheGroundFloor': '',
                  'TheGroundFloor': '',
                  'EstimatedCompletionDate': '',
                  'HousingCount': '',
                  'Floors': '',
                  'ElevatorHouse': '',
                  'IsHasElevator': '',
                  'ElevaltorInfo': '',
                  'BuildingStructure': '',
                  'BuildingType': '',
                  'BuildingHeight': '',
                  'BuildingCategory': '',
                  'Units': '',
                  'UnsoldAmount': '',
                  'BuildingAveragePrice': '',
                  'BuildingPriceRange': '',
                  'BuildingArea': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }

class HouseInfoItem(DjangoItem):
    django_model = HouseInfoWulumuqi
    fields_map = {'RecordTime': 'CurTimeStamp',
                  'CaseTime': '',
                  'ProjectName': '',
                  'ProjectUUID': 'ProjectUUID',
                  'RealEstateProjectID': '',
                  'BuildingName': 'BuildingName',
                  'BuildingUUID': 'BuildingUUID',
                  'BuildingID': '',
                  'DistrictName': '',
                  'UnitName': 'UnitName',
                  'UnitID': '',
                  'UnitUUID': '',
                  'HouseNumber': 'HouseNO',
                  'HouseName': 'HouseNO',
                  'HouseID': '',
                  'HouseUUID': 'HouseUUID',
                  'Address': '',
                  'FloorName': 'HouseFloor',
                  'ActualFloor': 'HouseFloor',
                  'FloorCount': '',
                  'FloorType': '',
                  'FloorHight': '',
                  'UnitShape': 'HouseType',
                  'UnitStructure': '',
                  'Rooms': '',
                  'Halls': '',
                  'Kitchens': '',
                  'Toilets': '',
                  'Balconys': '',
                  'UnenclosedBalconys': '',
                  'HouseShape': '',
                  'Dwelling': '',
                  'ForecastBuildingArea': '',
                  'ForecastInsideOfBuildingArea': '',
                  'ForecastPublicArea': '',
                  'MeasuredBuildingArea': 'HouseBuildingArea',
                  'MeasuredInsideOfBuildingArea': 'HouseInnerArea',
                  'MeasuredSharedPublicArea': '',
                  'MeasuredUndergroundArea': '',
                  'Toward': 'HouseOrientation',
                  'HouseType': '',
                  'HouseNature': '',
                  'Decoration': '',
                  'NatureOfPropertyRight': '',
                  'HouseUseType': 'HouseUsage',
                  'BuildingStructure': '',
                  'HouseSalePrice': '',
                  'SalePriceByBuildingArea': '',
                  'SalePriceByInsideOfBuildingArea': '',
                  'IsMortgage': '',
                  'IsAttachment': '',
                  'IsPrivateUse': '',
                  'IsMoveBack': '',
                  'IsSharedPublicMatching': '',
                  'SellState': '',
                  'SellSchedule': '',
                  'HouseState': 'HouseState',
                  'HouseStateLatest': 'HouseStateLatest',
                  'HouseLabel': '',
                  'HouseLabelLatest': '',
                  'TotalPrice': 'HousePrice',
                  'Price': 'RoughPrice',
                  'PriceType': '',
                  'DecorationPrice': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }