# coding = utf-8
from scrapy_djangoitem import DjangoItem
from HouseNew.models import *


class ProjectBaseItem(DjangoItem):
    django_model = ProjectBaseZhaoqing


class ProjectInfoItem(DjangoItem):
    django_model = ProjectInfoZhaoqing
    fields_map = {
        'RecordTime': '',
        'ProjectName': 'ProjectName',
        'PromotionName': '',
        'RealEstateProjectID': '',
        'ProjectUUID': 'ProjectUUID',
        'DistrictName': 'ProjectDistrict',
        'RegionName': '',
        'ProjectAddress': 'ProjectAddress',
        'ProjectType': '',
        'OnSaleState': '',
        'LandUse': '',
        'HousingCount': '',
        'Developer': 'ProjectCompany',
        'FloorArea': 'ProjectLandArea',
        'TotalBuidlingArea': 'ProjectBuildingArea',
        'BuildingType': '',
        'HouseUseType': 'ProjectUsage',
        'PropertyRightsDescription': '',
        'ProjectApproveData': '',
        'ProjectBookingData': '',
        'LssueDate': '',
        'PresalePermitNumber': '',
        'HouseBuildingCount': '',
        'ApprovalPresaleAmount': '',
        'ApprovalPresaleArea': '',
        'AveragePrice': '',
        'EarliestStartDate': '',
        'CompletionDate': '',
        'EarliestOpeningTime': '',
        'LatestDeliversHouseDate': '',
        'PresaleRegistrationManagementDepartment': '',
        'LandLevel': '',
        'GreeningRate': 'ProjectGreenRatio',
        'FloorAreaRatio': 'ProjectPlotRatio',
        'ManagementFees': '',
        'ManagementCompany': 'ProjectManageCompany',
        'OtheRights': '',
        'CertificateOfUseOfStateOwnedLand': 'ProjectLandLicense',
        'ConstructionPermitNumber': 'ProjectEngBuildingLicense',
        'QualificationNumber': '',
        'LandUsePermit': '',
        'BuildingPermit': 'ProjectEngPlanLicense',
        'LegalPersonNumber': '',
        'LegalPerson': '',
        'SourceUrl': '',
        'Decoration': '',
        'ParkingSpaceAmount': '',
        'Remarks': '',
        'ExtraJson': '',
    }


class BuildingInfoItem(DjangoItem):
    django_model = BuildingInfoZhaoqing
    fields_map = {
        'RecordTime': '',
        'ProjectName': 'ProjectName',
        'RealEstateProjectID': '',
        'ProjectUUID': 'ProjectUUID',
        'BuildingName': 'BuildingName',
        'BuildingID': '',
        'BuildingUUID': 'BuildingUUID',
        'UnitName': '',
        'UnitID': '',
        'UnitUUID': '',
        'PresalePermitNumber': 'BuildingRegName',
        'Address': '',
        'OnTheGroundFloor': '',
        'TheGroundFloor': '',
        'EstimatedCompletionDate': '',
        'HousingCount': '',
        'Floors': '',
        'ElevatorHouse': '',
        'IsHasElevator': '',
        'ElevaltorInfo': '',
        'BuildingStructure': '',
        'BuildingType': '',
        'BuildingHeight': '',
        'BuildingCategory': '',
        'Units': '',
        'UnsoldAmount': '',
        'BuildingAveragePrice': '',
        'BuildingPriceRange': '',
        'BuildingArea': '',
        'Remarks': '',
        'SourceUrl': '',
        'ExtraJson': '',
    }


class HouseInfoItem(DjangoItem):
    django_model = HouseInfoZhaoqing
    fields_map = {'RecordTime': '',
                  'CaseTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'BuildingName': 'BuildingName',
                  'BuildingID': '',
                  'BuildingUUID': 'BuildingUUID',
                  'DistrictName': '',
                  'UnitName': '',
                  'UnitID': '',
                  'UnitUUID': '',
                  'HouseNumber': '',
                  'HouseName': 'HouseName',
                  'HouseID': '',
                  'HouseUUID': 'HouseUUID',
                  'Address': '',
                  'FloorName': 'HouseFloor',
                  'ActualFloor': '',
                  'FloorCount': '',
                  'FloorType': '',
                  'FloorHight': '',
                  'UnitShape': '',
                  'UnitStructure': '',
                  'Rooms': '',
                  'Halls': '',
                  'Kitchens': '',
                  'Toilets': '',
                  'Balconys': '',
                  'UnenclosedBalconys': '',
                  'HouseShape': '',
                  'Dwelling': '',
                  'ForecastBuildingArea': '',
                  'ForecastInsideOfBuildingArea': '',
                  'ForecastPublicArea': '',
                  'MeasuredBuildingArea': 'HouseBuildingArea',
                  'MeasuredInsideOfBuildingArea': 'HouseInnerArea',
                  'MeasuredSharedPublicArea': '',
                  'MeasuredUndergroundArea': '',
                  'Toward': 'HouseOrientation',
                  'HouseType': '',
                  'HouseNature': '',
                  'Decoration': '',
                  'NatureOfPropertyRight': '',
                  'HouseUseType': 'HouseUsage',
                  'BuildingStructure': '',
                  'HouseSalePrice': 'HouseRegTotalPrice',
                  'SalePriceByBuildingArea': 'HouseRegUnitPrice',
                  'SalePriceByInsideOfBuildingArea': '',
                  'IsMortgage': '',
                  'IsAttachment': '',
                  'IsPrivateUse': '',
                  'IsMoveBack': '',
                  'IsSharedPublicMatching': '',
                  'SellState': '',
                  'SellSchedule': '',
                  'HouseState': 'HouseSaleState',
                  'HouseStateLatest': 'HouseSaleStateLatest',
                  'HouseLabel': '',
                  'HouseLabelLatest': '',
                  'TotalPrice': '',
                  'Price': '',
                  'PriceType': '',
                  'DecorationPrice': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }


class CompanyInfoItem(DjangoItem):
    django_model = CompanyInfoZhaoqing


class PresellInfoItem(DjangoItem):
    django_model = PreSellInfoZhaoqing
    fields_map = {'RecordTime': '',
                  'ProjectName': '',
                  'RealEstateProjectID': '',
                  'ProjectUUID': '',
                  'PresalePermitNumber': 'PreRegName',
                  'TotalBuidlingArea': '',
                  'ApprovalPresaleAmount': 'PreHouseNum',
                  'ApprovalPresaleArea': 'PreHouseArea',
                  'ApprovalPresaleHouseAmount': '',
                  'ApprovalPresaleHouseArea': '',
                  'PresaleBuildingAmount': '',
                  'ConstructionFloorCount': '',
                  'BuiltFloorCount': '',
                  'PeriodsCount': '',
                  'ConstructionTotalArea': '',
                  'GroundArea': '',
                  'UnderGroundArea': '',
                  'PresaleTotalBuidlingArea': '',
                  'Contacts': '',
                  'PresaleBuildingSupportingAreaInfo': '',
                  'PresaleHousingLandIsMortgage': '',
                  'ValidityDateStartDate': '',
                  'ValidityDateClosingDate': '',
                  'LssueDate': '',
                  'LssuingAuthority': '',
                  'PresaleRegistrationManagementDepartment': '',
                  'ValidityDateDescribe': 'PreLimitDate',
                  'ApprovalPresalePosition': '',
                  'LandUse': 'PreLandUsage',
                  'EarliestStartDate': '',
                  'LatestDeliversHouseDate': '',
                  'EarliestOpeningDate': 'PreOpenDate',
                  'HouseSpread': '',
                  'PresalePermitTie': '',
                  'PresaleHouseCount/PresaleUnitCount': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }
PreSellInfoItem = PresellInfoItem


class IndexInfoItem(DjangoItem):
    django_model = IndexInfoZhaoqing
