# coding = utf-8
from HouseNew.models import *
from scrapy_djangoitem import DjangoItem


class ProjectInfoItem(DjangoItem):
    django_model = ProjectDetailTianjin
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'PromotionName': '',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'DistrictName': 'DistrictName',
                  'RegionName': 'RegionName',
                  'ProjectAddress': 'ProjectAddress',
                  'ProjectType': '',
                  'OnSaleState': '',
                  'LandUse': 'Project_PlanType',
                  'HousingCount': '',
                  'Developer': 'Developer',
                  'FloorArea': 'FloorArea',
                  'TotalBuidlingArea': 'TotalBuidlingArea',
                  'BuildingType': '',
                  'HouseUseType': 'Project_Type',
                  'PropertyRightsDescription': '',
                  'ProjectApproveData': '',
                  'ProjectBookingData': '',
                  'LssueDate': '',
                  'PresalePermitNumber': '',
                  'HouseBuildingCount': '',
                  'ApprovalPresaleAmount': '',
                  'ApprovalPresaleArea': '',
                  'AveragePrice': '',
                  'EarliestStartDate': '',
                  'CompletionDate': '',
                  'EarliestOpeningTime': 'EarliestOpeningTime',
                  'LatestDeliversHouseDate': '',
                  'PresaleRegistrationManagementDepartment': '',
                  'LandLevel': '',
                  'GreeningRate': 'GreeningRate',
                  'FloorAreaRatio': 'FloorAreaRatio',
                  'ManagementFees': 'ManagementFees',
                  'ManagementCompany': 'ManagementCompany',
                  'OtheRights': '',
                  'CertificateOfUseOfStateOwnedLand': '',
                  'ConstructionPermitNumber': '',
                  'QualificationNumber': '',
                  'LandUsePermit': '',
                  'BuildingPermit': '',
                  'LegalPersonNumber': '',
                  'LegalPerson': '',
                  'SourceUrl': 'ProjectUrl',
                  'Decoration': '',
                  'ParkingSpaceAmount': 'ParkingSpaceAmount',
                  'Remarks': '',
                  'ExtraJson': '',
                  }


Project_Detail_Item = ProjectInfoItem


class BuildingInfoItem(DjangoItem):
    django_model = BuildingDetailTianjin
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'BuildingName': 'BuildingName',
                  'BuildingID': '',
                  'BuildingUUID': 'BuildingUUID',
                  'UnitName': '',
                  'UnitID': '',
                  'UnitUUID': '',
                  'PresalePermitNumber': 'SalePermitNumber',
                  'Address': '',
                  'OnTheGroundFloor': '',
                  'TheGroundFloor': '',
                  'EstimatedCompletionDate': '',
                  'HousingCount': 'HouseAmount',
                  'Floors': '',
                  'ElevatorHouse': '',
                  'IsHasElevator': '',
                  'ElevaltorInfo': '',
                  'BuildingStructure': '',
                  'BuildingType': '',
                  'BuildingHeight': '',
                  'BuildingCategory': '',
                  'Units': '',
                  'UnsoldAmount': 'OnsoldAmount',
                  'BuildingAveragePrice': '',
                  'BuildingPriceRange': '',
                  'BuildingArea': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }


Building_Detail_Item = BuildingInfoItem


class HouseInfoItem(DjangoItem):
    django_model = HouseDetailTianjin
    fields_map = {'RecordTime': '',
                  'CaseTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'BuildingName': 'BuildingName',
                  'BuildingID': '',
                  'BuildingUUID': 'BuildingUUID',
                  'DistrictName': '',
                  'UnitName': 'UnitName',
                  'UnitID': '',
                  'UnitUUID': 'UnitUUID',
                  'HouseNumber': '',
                  'HouseName': 'HouseName',
                  'HouseID': '',
                  'HouseUUID': 'HouseUUID',
                  'Address': '',
                  'FloorName': 'FloorName',
                  'ActualFloor': '',
                  'FloorCount': '',
                  'FloorType': '',
                  'FloorHight': 'FloorHight',
                  'UnitShape': 'UnitShape',
                  'UnitStructure': '',
                  'Rooms': '',
                  'Halls': '',
                  'Kitchens': '',
                  'Toilets': '',
                  'Balconys': '',
                  'UnenclosedBalconys': '',
                  'HouseShape': '',
                  'Dwelling': '',
                  'ForecastBuildingArea': '',
                  'ForecastInsideOfBuildingArea': '',
                  'ForecastPublicArea': '',
                  'MeasuredBuildingArea': 'MeasuredBuildingArea',
                  'MeasuredInsideOfBuildingArea': 'MeasuredInsideOfBuildingArea',
                  'MeasuredSharedPublicArea': 'MeasuredSharedPublicArea',
                  'MeasuredUndergroundArea': '',
                  'Toward': 'Toward',
                  'HouseType': '',
                  'HouseNature': '',
                  'Decoration': '',
                  'NatureOfPropertyRight': '',
                  'HouseUseType': 'HouseUseType',
                  'BuildingStructure': 'BuildingStructure',
                  'HouseSalePrice': '',
                  'SalePriceByBuildingArea': '',
                  'SalePriceByInsideOfBuildingArea': 'SalePriceByInsideOfBuildingArea',
                  'IsMortgage': '',
                  'IsAttachment': '',
                  'IsPrivateUse': '',
                  'IsMoveBack': '',
                  'IsSharedPublicMatching': '',
                  'SellState': '',
                  'SellSchedule': '',
                  'HouseState': 'HouseSaleState',
                  'HouseStateLatest': 'HouseSaleStateLatest',
                  'HouseLabel': '',
                  'HouseLabelLatest': '',
                  'TotalPrice': '',
                  'Price': '',
                  'PriceType': '',
                  'DecorationPrice': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }


House_Detail_Item = HouseInfoItem
