# coding = utf-8
from scrapy_djangoitem import DjangoItem
from HouseNew.models import *


class ProjectBaseItem(DjangoItem):
    django_model = None


class ProjectInfoItem(DjangoItem):
    django_model = ProjectInfoHefei
    fields_map = {
        'RecordTime': '',
        'ProjectName': 'ProjectName',
        'PromotionName': '',
        'RealEstateProjectID': '',
        'ProjectUUID': 'ProjectUUID',
        'DistrictName': 'ProjectDistrict',
        'RegionName': '',
        'ProjectAddress': 'ProjectAddress',
        'ProjectType': '',
        'OnSaleState': '',
        'LandUse': '',
        'HousingCount': '',
        'Developer': 'ProjectDevelopCompany',
        'FloorArea': '',
        'TotalBuidlingArea': 'ProjectBuildingArea',
        'BuildingType': '',
        'HouseUseType': '',
        'PropertyRightsDescription': '',
        'ProjectApproveData': '',
        'ProjectBookingData': '',
        'LssueDate': '',
        'PresalePermitNumber': '',
        'HouseBuildingCount': '',
        'ApprovalPresaleAmount': '',
        'ApprovalPresaleArea': '',
        'AveragePrice': '',
        'EarliestStartDate': '',
        'CompletionDate': '',
        'EarliestOpeningTime': '',
        'LatestDeliversHouseDate': '',
        'PresaleRegistrationManagementDepartment': '',
        'LandLevel': '',
        'GreeningRate': 'ProjectGreenRatio',
        'FloorAreaRatio': 'ProjectPlotRatio',
        'ManagementFees': '',
        'ManagementCompany': 'ProjectManageCompany',
        'OtheRights': '',
        'CertificateOfUseOfStateOwnedLand': '',
        'ConstructionPermitNumber': '',
        'QualificationNumber': '',
        'LandUsePermit': '',
        'BuildingPermit': '',
        'LegalPersonNumber': '',
        'LegalPerson': '',
        'SourceUrl': '',
        'Decoration': '',
        'ParkingSpaceAmount': '',
        'Remarks': '',
        'ExtraJson': '',
    }


class BuildingInfoItem(DjangoItem):
    django_model = BuildingInfoHefei
    fields_map = {
        'RecordTime': '',
        'ProjectName': 'ProjectName',
        'RealEstateProjectID': '',
        'ProjectUUID': 'ProjectUUID',
        'BuildingName': 'BuildingName',
        'BuildingID': '',
        'BuildingUUID': 'BuildingUUID',
        'UnitName': '',
        'UnitID': '',
        'UnitUUID': '',
        'PresalePermitNumber': 'BuildingRegName',
        'Address': '',
        'OnTheGroundFloor': 'BuildingFloorAbove',
        'TheGroundFloor': 'BuildingFloorBelow',
        'EstimatedCompletionDate': 'BuildingCompleteDate',
        'HousingCount': '',
        'Floors': '',
        'ElevatorHouse': '',
        'IsHasElevator': '',
        'ElevaltorInfo': '',
        'BuildingStructure': 'BuildingStructure',
        'BuildingType': '',
        'BuildingHeight': '',
        'BuildingCategory': '',
        'Units': '',
        'UnsoldAmount': '',
        'BuildingAveragePrice': '',
        'BuildingPriceRange': '',
        'BuildingArea': 'BuildingPreSellArea',
        'Remarks': '',
        'SourceUrl': '',
        'ExtraJson': '',
    }


class HouseInfoItem(DjangoItem):
    django_model = HouseInfoHefei
    fields_map = {
        'RecordTime': '',
        'CaseTime': '',
        'ProjectName': 'ProjectName',
        'RealEstateProjectID': '',
        'ProjectUUID': 'ProjectUUID',
        'BuildingName': 'BuildingName',
        'BuildingID': '',
        'BuildingUUID': 'BuildingUUID',
        'DistrictName': '',
        'UnitName': '',
        'UnitID': '',
        'UnitUUID': '',
        'HouseNumber': 'HouseNum',
        'HouseName': 'HouseName',
        'HouseID': '',
        'HouseUUID': 'HouseUUID',
        'Address': 'HouseAddress',
        'FloorName': 'HouseFloor',
        'ActualFloor': '',
        'FloorCount': '',
        'FloorType': '',
        'FloorHight': '',
        'UnitShape': '',
        'UnitStructure': '',
        'Rooms': '',
        'Halls': '',
        'Kitchens': '',
        'Toilets': '',
        'Balconys': '',
        'UnenclosedBalconys': '',
        'HouseShape': '',
        'Dwelling': '',
        'ForecastBuildingArea': '',
        'ForecastInsideOfBuildingArea': '',
        'ForecastPublicArea': '',
        'MeasuredBuildingArea': 'HouseBuildingArea',
        'MeasuredInsideOfBuildingArea': 'HouseInnerArea',
        'MeasuredSharedPublicArea': 'HouseShareArea',
        'MeasuredUndergroundArea': '',
        'Toward': '',
        'HouseType': '',
        'HouseNature': '',
        'Decoration': '',
        'NatureOfPropertyRight': '',
        'HouseUseType': 'HouseUsage',
        'BuildingStructure': 'HouseStructure',
        'HouseSalePrice': '',
        'SalePriceByBuildingArea': '',
        'SalePriceByInsideOfBuildingArea': '',
        'IsMortgage': '',
        'IsAttachment': '',
        'IsPrivateUse': '',
        'IsMoveBack': '',
        'IsSharedPublicMatching': '',
        'SellState': '',
        'SellSchedule': '',
        'HouseState': 'HouseSaleState',
        'HouseStateLatest': 'HouseSaleStateLatest',
        'HouseLabel': '',
        'HouseLabelLatest': '',
        'TotalPrice': '',
        'Price': '',
        'PriceType': '',
        'DecorationPrice': '',
        'Remarks': '',
        'SourceUrl': '',
        'ExtraJson': '',
    }
