# coding = utf-8
from scrapy_djangoitem import DjangoItem
from HouseNew.models import *


class ProjectInfoItem(DjangoItem):
    django_model = ProjectBaseQingdao
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'PromotionName': '',
                  'RealEstateProjectID': 'ProjectID',
                  'ProjectUUID': 'ProjectUUID',
                  'DistrictName': 'DistrictName',
                  'RegionName': 'RegionName',
                  'ProjectAddress': 'ProjectAddress',
                  'ProjectType': '',
                  'OnSaleState': 'OnSaleState',
                  'LandUse': '',
                  'HousingCount': 'TotalAmount',
                  'Developer': 'Developer',
                  'FloorArea': '',
                  'TotalBuidlingArea': 'TotalArea',
                  'BuildingType': '',
                  'HouseUseType': '',
                  'PropertyRightsDescription': '',
                  'ProjectApproveData': '',
                  'ProjectBookingData': '',
                  'LssueDate': '',
                  'PresalePermitNumber': '',
                  'HouseBuildingCount': '',
                  'ApprovalPresaleAmount': '',
                  'ApprovalPresaleArea': '',
                  'AveragePrice': '',
                  'EarliestStartDate': '',
                  'CompletionDate': '',
                  'EarliestOpeningTime': '',
                  'LatestDeliversHouseDate': '',
                  'PresaleRegistrationManagementDepartment': '',
                  'LandLevel': '',
                  'GreeningRate': '',
                  'FloorAreaRatio': '',
                  'ManagementFees': '',
                  'ManagementCompany': '',
                  'OtheRights': '',
                  'CertificateOfUseOfStateOwnedLand': '',
                  'ConstructionPermitNumber': '',
                  'QualificationNumber': '',
                  'LandUsePermit': '',
                  'BuildingPermit': '',
                  'LegalPersonNumber': '',
                  'LegalPerson': '',
                  'SourceUrl': '',
                  'Decoration': '',
                  'ParkingSpaceAmount': '',
                  'Remarks': '',
                  'ExtraJson': '',
                  }


ProjectBaseItem = ProjectInfoItem


class PresellInfoItem(DjangoItem):
    django_model = PresellInfoQingdao
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'PresalePermitNumber': 'PresalePermitName',
                  'TotalBuidlingArea': 'TotalArea',
                  'ApprovalPresaleAmount': 'TotalAmount',
                  'ApprovalPresaleArea': 'TotalArea',
                  'ApprovalPresaleHouseAmount': '',
                  'ApprovalPresaleHouseArea': '',
                  'PresaleBuildingAmount': '',
                  'ConstructionFloorCount': '',
                  'BuiltFloorCount': '',
                  'PeriodsCount': '',
                  'ConstructionTotalArea': '',
                  'GroundArea': '',
                  'UnderGroundArea': '',
                  'PresaleTotalBuidlingArea': 'TotalArea',
                  'Contacts': '',
                  'PresaleBuildingSupportingAreaInfo': '',
                  'PresaleHousingLandIsMortgage': '',
                  'ValidityDateStartDate': '',
                  'ValidityDateClosingDate': '',
                  'LssueDate': '',
                  'LssuingAuthority': '',
                  'PresaleRegistrationManagementDepartment': '',
                  'ValidityDateDescribe': '',
                  'ApprovalPresalePosition': '',
                  'LandUse': 'LandUse',
                  'EarliestStartDate': '',
                  'LatestDeliversHouseDate': '',
                  'EarliestOpeningDate': 'EarliestOpeningDate',
                  'HouseSpread': '',
                  'PresalePermitTie': '',
                  'PresaleHouseCount/PresaleUnitCount': '',
                  'Remarks': '',
                  'SourceUrl': '',
                  'ExtraJson': '',
                  }


class BuildingInfoItem(DjangoItem):
    django_model = BuildingInfoQingdao
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'ProjectUUID': 'ProjectUUID',
                  'RealEstateProjectID': '',
                  'BuildingName': 'BuildingName',
                  'BuildingID': 'BuildingID',
                  'BuildingUUID': 'BuildingUUID',
                  'UnitName': '',
                  'UnitID': '',
                  'UnitUUID': '',
                  'PresalePermitNumber': 'PresalePermitName',
                  'Address': '',
                  'OnTheGroundFloor': '',
                  'TheGroundFloor': '',
                  'EstimatedCompletionDate': '',
                  'HousingCount': '',
                  'Floors': '',
                  'ElevatorHouse': '',
                  'IsHasElevator': '',
                  'ElevaltorInfo': '',
                  'BuildingStructure': '',
                  'BuildingType': '',
                  'BuildingHeight': '',
                  'BuildingCategory': '',
                  'Units': '',
                  'UnsoldAmount': '',
                  'BuildingAveragePrice': 'BuildingReferencePrice',
                  'BuildingPriceRange': '',
                  'BuildingArea': '',
                  'Remarks': '',
                  'SourceUrl': 'BuildingURL',
                  'ExtraJson': '',
                  }


class HouseInfoItem(DjangoItem):
    django_model = HouseInfoQingdao
    fields_map = {'RecordTime': '',
                  'CaseTime': '',
                  'ProjectName': 'ProjectName',
                  'ProjectUUID': 'ProjectUUID',
                  'RealEstateProjectID': '',
                  'BuildingName': 'BuildingName',
                  'BuildingUUID': 'BuildingUUID',
                  'BuildingID': '',
                  'DistrictName': '',
                  'UnitName': 'UnitName',
                  'UnitID': '',
                  'UnitUUID': '',
                  'HouseNumber': 'HouseNumber',
                  'HouseName': 'HouseName',
                  'HouseID': 'HouseID',
                  'HouseUUID': 'HouseUUID',
                  'Address': '',
                  'FloorName': 'FloorName',
                  'ActualFloor': 'ActualFloor',
                  'FloorCount': '',
                  'FloorType': '',
                  'FloorHight': '',
                  'UnitShape': 'HouseUnitShape',
                  'UnitStructure': '',
                  'Rooms': '',
                  'Halls': '',
                  'Kitchens': '',
                  'Toilets': '',
                  'Balconys': '',
                  'UnenclosedBalconys': '',
                  'HouseShape': '',
                  'Dwelling': '',
                  'ForecastBuildingArea': 'ForecastBuildingArea',
                  'ForecastInsideOfBuildingArea': 'ForecastInsideOfBuildingArea',
                  'ForecastPublicArea': 'ForecastPublicArea',
                  'MeasuredBuildingArea': 'MeasuredBuildingArea',
                  'MeasuredInsideOfBuildingArea': 'MeasuredInsideOfBuildingArea',
                  'MeasuredSharedPublicArea': 'MeasuredSharedPublicArea',
                  'MeasuredUndergroundArea': '',
                  'Toward': '',
                  'HouseType': '',
                  'HouseNature': '',
                  'Decoration': '',
                  'NatureOfPropertyRight': '',
                  'HouseUseType': 'HouseUseType',
                  'BuildingStructure': 'BuildingStructure',
                  'HouseSalePrice': '',
                  'SalePriceByBuildingArea': '',
                  'SalePriceByInsideOfBuildingArea': '',
                  'IsMortgage': '',
                  'IsAttachment': '',
                  'IsPrivateUse': '',
                  'IsMoveBack': '',
                  'IsSharedPublicMatching': '',
                  'SellState': '',
                  'SellSchedule': '',
                  'HouseState': 'HouseState',
                  'HouseStateLatest': 'HouseStateLatest',
                  'HouseLabel': '',
                  'HouseLabelLatest': '',
                  'TotalPrice': '',
                  'Price': '',
                  'PriceType': '',
                  'DecorationPrice': '',
                  'Remarks': '',
                  'SourceUrl': 'SourceUrl',
                  'ExtraJson': '',
                  }
