# coding = utf-8
from scrapy_djangoitem import DjangoItem
from HouseNew.models import *


class ProjectBaseItem(DjangoItem):
    django_model = ProjectBaseDongguan


class ProjectInfoItem(DjangoItem):
    django_model = ProjectInfoDongguan
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'PromotionName': 'ProjectAlias',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'DistrictName': '',
                  'RegionName': '',
                  'ProjectAddress': 'ProjectAddress',
                  'ProjectType': '',
                  'OnSaleState': '',
                  'LandUse': 'ProjectUsage',
                  'HousingCount': 'ProjectHouseNum',
                  'Developer': 'ProjectCompany',
                  'FloorArea': 'ProjectArea',
                  'TotalBuidlingArea': '',
                  'BuildingType': '',
                  'HouseUseType': '',
                  'PropertyRightsDescription': '',
                  'ProjectApproveData': '',
                  'ProjectBookingData': '',
                  'LssueDate': '',
                  'PresalePermitNumber': 'ProjectRegName',
                  'HouseBuildingCount': '',
                  'ApprovalPresaleAmount': '',
                  'ApprovalPresaleArea': '',
                  'AveragePrice': '',
                  'EarliestStartDate': '',
                  'CompletionDate': '',
                  'EarliestOpeningTime': 'ProjectOpenDate',
                  'LatestDeliversHouseDate': '',
                  'PresaleRegistrationManagementDepartment': '',
                  'LandLevel': '',
                  'GreeningRate': '',
                  'FloorAreaRatio': '',
                  'ManagementFees': '',
                  'ManagementCompany': '',
                  'OtheRights': '',
                  'CertificateOfUseOfStateOwnedLand': '',
                  'ConstructionPermitNumber': 'ProjectConstructionLicenseCode',
                  'QualificationNumber': '',
                  'LandUsePermit': 'ProjectAreaPlanLicenseCode',
                  'BuildingPermit': 'ProjectPlanLicenseCode',
                  'LegalPersonNumber': '',
                  'LegalPerson': 'ProjectCorporation',
                  'SourceUrl': 'SourceUrl',
                  'Decoration': '',
                  'ParkingSpaceAmount': '',
                  'Remarks': '',
                  'ExtraJson': '',
                  }


class BuildingInfoItem(DjangoItem):
    django_model = BuildingInfoDongguan
    fields_map = {'RecordTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'BuildingName': 'BuildingName',
                  'BuildingID': '',
                  'BuildingUUID': 'BuildingUUID',
                  'UnitName': '',
                  'UnitID': '',
                  'UnitUUID': '',
                  'PresalePermitNumber': 'ProjectRegName',
                  'Address': '',
                  'OnTheGroundFloor': '',
                  'TheGroundFloor': '',
                  'EstimatedCompletionDate': '',
                  'HousingCount': 'BuildingHouseNum',
                  'Floors': 'BuildingFloorNum',
                  'ElevatorHouse': '',
                  'IsHasElevator': '',
                  'ElevaltorInfo': '',
                  'BuildingStructure': '',
                  'BuildingType': '',
                  'BuildingHeight': '',
                  'BuildingCategory': '',
                  'Units': '',
                  'UnsoldAmount': '',
                  'BuildingAveragePrice': '',
                  'BuildingPriceRange': '',
                  'BuildingArea': '',
                  'Remarks': '',
                  'SourceUrl': 'SourceUrl',
                  'ExtraJson': '',
                  }


class HouseInfoItem(DjangoItem):
    django_model = HouseInfoDongguan
    fields_map = {'RecordTime': '',
                  'CaseTime': '',
                  'ProjectName': 'ProjectName',
                  'RealEstateProjectID': '',
                  'ProjectUUID': 'ProjectUUID',
                  'BuildingName': 'BuildingName',
                  'BuildingID': '',
                  'BuildingUUID': 'BuildingUUID',
                  'DistrictName': '',
                  'UnitName': '',
                  'UnitID': '',
                  'UnitUUID': '',
                  'HouseNumber': '',
                  'HouseName': 'HouseName',
                  'HouseID': '',
                  'HouseUUID': 'HouseUUID',
                  'Address': '',
                  'FloorName': 'HouseFloor',
                  'ActualFloor': 'HouseFloorCross',
                  'FloorCount': '',
                  'FloorType': '',
                  'FloorHight': '',
                  'UnitShape': '',
                  'UnitStructure': '',
                  'Rooms': '',
                  'Halls': '',
                  'Kitchens': '',
                  'Toilets': '',
                  'Balconys': '',
                  'UnenclosedBalconys': '',
                  'HouseShape': '',
                  'Dwelling': '',
                  'ForecastBuildingArea': '',
                  'ForecastInsideOfBuildingArea': '',
                  'ForecastPublicArea': '',
                  'MeasuredBuildingArea': 'HouseBuildingArea',
                  'MeasuredInsideOfBuildingArea': 'HouseInnerArea',
                  'MeasuredSharedPublicArea': 'HouseShareArea',
                  'MeasuredUndergroundArea': '',
                  'Toward': '',
                  'HouseType': '',
                  'HouseNature': '',
                  'Decoration': '',
                  'NatureOfPropertyRight': '',
                  'HouseUseType': 'HouseUsage',
                  'BuildingStructure': '',
                  'HouseSalePrice': '',
                  'SalePriceByBuildingArea': '',
                  'SalePriceByInsideOfBuildingArea': '',
                  'IsMortgage': 'HousePledgeState',
                  'IsAttachment': 'HouseAttachState',
                  'IsPrivateUse': '',
                  'IsMoveBack': '',
                  'IsSharedPublicMatching': '',
                  'SellState': '',
                  'SellSchedule': '',
                  'HouseState': 'HouseState',
                  'HouseStateLatest': 'HouseStateLatest',
                  'HouseLabel': '',
                  'HouseLabelLatest': '',
                  'TotalPrice': 'HousePrice',
                  'Price': 'HouseUnitPrice',
                  'PriceType': '',
                  'DecorationPrice': '',
                  'Remarks': '',
                  'SourceUrl': 'SourceUrl',
                  'ExtraJson': '',
                  }
