# encoding = utf-8
from HouseNewModels.GuiyangModels import *
from HouseNewModels.TaiyuanModels import *
from HouseNewModels.ChangzhouModels import *
from HouseNewModels.HefeiModels import *
from HouseNewModels.DalianModels import *
from HouseNewModels.DongguanModels import *
from HouseNewModels.ChangshaModels import *
from HouseNewModels.HangzhouModels import *
from HouseNewModels.ChongqingModels import *
from HouseNewModels.NanchangModels import *
from HouseNewModels.NantongModels import *
from HouseNewModels.QuanzhouModels import *
from HouseNewModels.JiujiangModels import *
from HouseNewModels.JinanModels import *
from HouseNewModels.ZhaoqingModels import *
from HouseNewModels.SuzhouModels import *
from HouseNewModels.FuzhouModels import *
