# encoding = utf-8
from HouseNew.HouseNewModels.GuiyangModels import *
from HouseNew.HouseNewModels.TaiyuanModels import *
from HouseNew.HouseNewModels.ChangzhouModels import *
from HouseNew.HouseNewModels.HefeiModels import *
from HouseNew.HouseNewModels.DalianModels import *
from HouseNew.HouseNewModels.DongguanModels import *
from HouseNew.HouseNewModels.ChangshaModels import *
from HouseNew.HouseNewModels.HangzhouModels import *
from HouseNew.HouseNewModels.ChongqingModels import *
from HouseNew.HouseNewModels.NanchangModels import *
from HouseNew.HouseNewModels.NantongModels import *
from HouseNew.HouseNewModels.QuanzhouModels import *
from HouseNew.HouseNewModels.JiujiangModels import *
from HouseNew.HouseNewModels.JinanModels import *
from HouseNew.HouseNewModels.ZhaoqingModels import *
from HouseNew.HouseNewModels.SuzhouModels import *
from HouseNew.HouseNewModels.FuzhouModels import *
from HouseNew.HouseNewModels.GuangzhouModels import *
from HouseNew.HouseNewModels.QingdaoModels import *
from HouseNew.HouseNewModels.WulumuqiModels import *
from HouseNew.HouseNewModels.NanjingModels import *
from HouseNew.HouseNewModels.MaomingModels import *
from HouseNew.HouseNewModels.YangjiangModels import *
from HouseNew.HouseNewModels.YunfuModels import *
from HouseNew.HouseNewModels.QingyuanModels import *
from HouseNew.HouseNewModels.HeyuanModels import *
from HouseNew.HouseNewModels.WuhanModels import *
from HouseNew.HouseNewModels.XuzhouModels import *
from HouseNew.HouseNewModels.TianjinModels import *
